- components/ValaxyMermaid.vue
- valaxy.config.ts
Made a dedicated Mermaid render component, and now Mermaid can be rendered.
> fix: fix mermaid render error

- components/AutoLanguageDetector.vue
- layouts/default.vue
- layouts/home.vue
- utils/languageDetector.ts
The default language of this site is English, no matter what language the user is, you need to switch it manually
Now, the auto-detect language feature has been added to automatically switch to the browser language on the first visit.
> feat(i18n): add auto switch language from browser settings

- .valaxy/typed-router.d.ts
- components/PressNavBar.vue
- locales/en.yml
- locales/zh-CN.yml
- pages/pricing.md
- valaxy.config.ts
1. 删除标题定冠词 `The`
2. 移除 Pricing 页面和 Nav Menu
3. 文档 Nav 标题改成 i18n
> chore: docs title & nav

- components/BackToTop.vue
- layouts/default.vue
- layouts/home.vue
- locales/en.yml
- locales/zh-CN.yml
- valaxy.config.ts
> feat: add back-to-top button

- pages/guide/drivers/google_photos.md
> docs: 修复谷歌相册的多语言、新增文件可操作范围的提示

- CONTRIBUTE.md
- README.cn.md
- README.md
- pages/configuration/global.md
- pages/configuration/other.md
- pages/ecosystem/official_desktop.md
- pages/faq/seealso.md
- pages/guide/advanced/ftp.md
- pages/guide/advanced/ipa.md
- pages/guide/advanced/offline-download.md
- pages/guide/advanced/search.md
- pages/guide/advanced/sso.md
- pages/guide/drivers/feiji.md
- pages/guide/installation/manual.md
- pages/guide/installation/reverse-proxy.md
- pages/migration/alist-v3.md
- styles/index.scss
> Format and add OpenList-Desktop Docs

- public/algolia-verify.html
> docs: add algolia verification

- valaxy.config.ts
> feat: add algolia search

- pages/guide/drivers/139.md
fix document format and translation
> docs(139): fix typo

- pages/guide/drivers/115.md
> docs(115): update video tutorial link to latest

- pages/configuration/configuration.md
https://github.com/OpenListTeam/OpenList/pull/816
> refactor(config): log filter

- valaxy.config.ts
1. update date format from '2025-07-25T02:06:08.969Z' to '2025/7/25 10:05:53'
2. fix an issue when DOCS_COMMIT_SHA is undefined, only show built time
> fix(docs): update built date format and footer message logic

- pages/guide/installation/reverse-proxy.md
> docs: update reverse-proxy

- pages/guide/advanced/offline-download.md
> refactor(offline-download): add qBittorrent and Transmission Docker Compose examples

- pages/guide/installation/script.md
> docs(script): add descriptions for multiarch support in the install script

- pages/configuration/configuration.md
Close: https://github.com/OpenListTeam/OpenList/issues/872
> docs(configuration): update CDN instructions for Lite version

- pages/guide/advanced/offline-download.md
Related to #108 
Github不是很会使用 抱歉
> docs(offline-download): fix typo

- pages/configuration/configuration.md
- pages/guide/advanced/search.md
> docs(search): improve docs about `meilisearch` (OpenListTeam/OpenList#864)

- pages/ecosystem/index.md
- pages/ecosystem/official_mobile.md
> docs: add OpenList-Mobile docs

- pages/guide/drivers/webdav.md
> docs: add a new method for solving OneDrive 403

- pages/api/public.md
> docs(api): fix typo "pcr"

- pages/guide/drivers/189.md
> docs(189): updated validation of removal schemes and added speed limit hints

- locales/en.yml
- locales/zh-CN.yml
- pages/faq/howto.md
- pages/index.md
- valaxy.config.ts
> docs: fix & improve SEO

- pages/faq/howto.md
- pages/faq/why.md
- pages/guide/advanced/alias.md
- pages/guide/advanced/balance.md
> fix(docs): remove zero-width-spaces(u+200b) from documentation content

- .github/PULL_REQUEST_TEMPLATE.md
为OpenList-Docs加入了Pull Request模板
OpenList-Docs 仓库缺乏标准化的 PR 模板，这可能导致 PR 提交不一致，并使维护者难以高效地审查贡献。此模板确保贡献者提供所有必要信息并遵循项目的贡献准则。
我已阅读 [CONTRIBUTING](https://github.com/OpenListTeam/OpenList-Docs/blob/main/CONTRIBUTING.md) 文档。
我已使用 [prettier](https://prettier.io/) 或其他适当的格式化工具格式化提交的代码或文档。
我已为所有支持语言（包括中文和英文）更新文档内容。 (若适用)
我已确认编写的文档或代码格式正确, 无语法错误, 拼写错误。
我已相应更新了相关仓库（若适用）。
> docs(contributing): update guidelines

- pages/ecosystem/index.md
修复了Ecosystem文档格式，并且加入了一个用于提交的提示
我已阅读 [CONTRIBUTING](https://github.com/OpenListTeam/OpenList-Docs/blob/main/CONTRIBUTING.md) 文档。
我已使用 [prettier](https://prettier.io/) 或其他适当的格式化工具格式化提交的代码或文档。
我已为所有支持语言（包括中文和英文）更新文档内容。 (若适用)
我已确认编写的文档或代码格式正确, 无语法错误, 拼写错误。
我已相应更新了相关仓库（若适用）。
> docs(ecosystem): fix format & add submit tip

- pages/guide/advanced/rapid_upload.md
- pages/guide/advanced/sso.md
- pages/guide/drivers/115.md
- pages/guide/drivers/139.md
- pages/guide/drivers/189.md
- pages/guide/drivers/halalcloud.md
- pages/guide/drivers/onedrive_app.md
- pages/guide/drivers/pikpak.md
- pages/guide/drivers/quark.md
- pages/guide/drivers/thunder.md
- pages/guide/drivers/url_tree.md
> docs(all): replace invalid superscript syntax

- pages/faq/seealso.md
- Added missing '[' to Bilibili links for proper formatting
- Moved advisory note to language-specific sections
- Added Chinese version for zh-CN users
- Verified all links render correctly
> docs(faq/seealso): fix broken links and add Chinese note

- pages/guide/drivers/openlist.md
重新添加在旧版文档 [e76d33_en](https://github.com/OpenListTeam/docs/commit/e76d33055fd28140fa74c4e48b6ecc63832072e2#diff-b7d611e12a4e958d5ea2e9f39fa309c9a619cbcd75678deaac71f4a6e9b30bf0) [e76d33_zh](https://github.com/OpenListTeam/docs/commit/e76d33055fd28140fa74c4e48b6ecc63832072e2#diff-b40bde56d8f62c6a22ba65f8c88f4aa9a00a64cb1de99f6d3b6dc5487779f871) 中被移除后一直没有重新添加回来 OpenList  的挂载指南
重新加入了 OpenList 的挂载指南
Closes #191
我已阅读 [CONTRIBUTING](https://github.com/OpenListTeam/OpenList-Docs/blob/main/CONTRIBUTING.md) 文档。
我已使用 [prettier](https://prettier.io/) 或其他适当的格式化工具格式化提交的代码或文档。
我已为所有支持语言（包括中文和英文）更新文档内容。 (若适用)
我已确认编写的文档或代码格式正确, 无语法错误, 拼写错误。
我已相应更新了相关仓库（若适用）。
> docs(drivers): add mount OpenList guide
